disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Embedded Leadership"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo.svg"
  description = "Blog about embedded systems, software engineering, leadership, management, and technology."

  [[params.author.links]]
    github = "https://github.com/cledouarec"

  [[params.author.links]]
    linkedin = "https://www.linkedin.com/in/christophe-le-douarec/"

  ["params.author"]
    name = "Christophe Le Douarec"
    image = "LE DOUAREC Christophe.jpg"
    headline = "Experienced software leader with a strong background in embedded products, organizational improvement, and R&D leadership aligned with business goals."
    bio = "Experienced software leader with a strong background in embedded products, organizational improvement, and R&D leadership aligned with business goals."