[[main]]
  none = "none"

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 1

[[main]]
  identifier = "categories"
  name = "Categories"
  pageRef = "categories"
  weight = 2

[[main]]
  name = "People Management"
  parent = "categories"
  pageRef = "people-management"
  weight = 21

[[main]]
  name = "Product Management"
  parent = "categories"
  pageRef = "product-management"
  weight = 22

[[main]]
  name = "Organization"
  parent = "categories"
  pageRef = "organization"
  weight = 23

[[main]]
  name = "Tech"
  parent = "categories"
  pageRef = "tech"
  weight = 24

[[main]]
  name = "About"
  pageRef = "about"
  weight = 3

[[footer]]
  none = "none"